import fs from "node:fs";
import path from "node:path";
import type { Action } from "../core/install-fs.js";
import { backup, writeFile } from "../core/install-fs.js";
import type { InstallContext, SkillStatus } from "./types.js";

/** Marker placed in generated per-skill files so uninstall only removes our own files. */
export const MANAGED_LINE = "<!-- generated by agent-skills — edit the source skill, not this file -->";

/** Whether a generated file carries our marker (so it's safe to overwrite/remove). */
function fileIsManaged(file: string): boolean {
	return fs.existsSync(file) && fs.readFileSync(file, "utf8").includes(MANAGED_LINE);
}

/**
 * Render a flat frontmatter block from string/boolean values. Deterministic and
 * dependency-free (values are single-line only, which suits skill metadata).
 *
 * @param fields - Ordered key/value pairs (undefined values are skipped).
 * @returns A `---`-delimited YAML frontmatter block, no trailing newline.
 */
export function frontmatter(fields: Record<string, string | boolean | undefined>): string {
	const lines = ["---"];
	for (const [key, value] of Object.entries(fields)) {
		if (value === undefined) continue;
		lines.push(typeof value === "boolean" ? `${key}: ${value}` : `${key}: ${escapeYaml(value)}`);
	}
	lines.push("---");
	return lines.join("\n");
}

/**
 * Quote a frontmatter value unless it's a plain scalar free of every
 * YAML-significant character. The unquoted set deliberately excludes `:`, `#`,
 * `&`, and other indicators, so a description like "Out of scope: …" or one with
 * a "#tag" is JSON-quoted rather than emitted as invalid/misparsed YAML.
 *
 * @param value - The raw value.
 * @returns The value, quoted only if it needs to be.
 */
function escapeYaml(value: string): string {
	return /^[\w .,/()'+-]+$/.test(value) ? value : JSON.stringify(value);
}

/**
 * Install one generated file per skill under `ctx.dest`, e.g. `<name>.mdc`.
 * Shared by the file-per-skill adapters (cursor, windsurf). An unmanaged file of
 * the same name (one the user hand-wrote) is left alone unless `--force`, in which
 * case it's backed up before being overwritten.
 *
 * @param ctx - Install context.
 * @param ext - File extension (no dot).
 * @param build - Renders a skill's file contents.
 * @returns The recorded actions.
 */
export function installFilePerSkill(ctx: InstallContext, ext: string, build: (skill: InstallContext["skills"][number]) => string): Action[] {
	// A user's legacy single FILE at ctx.dest (e.g. the classic `.clinerules` file, where we
	// want a `.clinerules/` directory) would make mkdir(ctx.dest) throw EEXIST. Treat it like
	// any other unmanaged entry: skip, or back it up (move aside) under --force.
	if (fs.existsSync(ctx.dest) && fs.statSync(ctx.dest).isFile()) {
		if (!ctx.force)
			return [{ verb: "skip", path: ctx.dest, note: "exists as a file, not a directory — not managed; use --force to move it aside" }];
		const backedUp = backup(ctx.dest, Date.now(), ctx.dryRun);
		return [backedUp, ...ctx.skills.map((skill) => writeFile(path.join(ctx.dest, `${skill.name}.${ext}`), build(skill), ctx.dryRun))];
	}
	return ctx.skills.flatMap((skill) => {
		const file = path.join(ctx.dest, `${skill.name}.${ext}`);
		if (fs.existsSync(file) && !fileIsManaged(file)) {
			if (!ctx.force) return [{ verb: "skip", path: file, note: "exists, not managed by agent-skills — use --force to overwrite" }];
			return [backup(file, Date.now(), ctx.dryRun), writeFile(file, build(skill), ctx.dryRun)];
		}
		return [writeFile(file, build(skill), ctx.dryRun)];
	});
}

/**
 * Report the on-disk state of each per-skill generated file (for `doctor`).
 *
 * @param ctx - Install context.
 * @param ext - File extension (no dot).
 * @param build - Renders the expected file contents (to detect drift).
 * @returns Per-skill statuses.
 */
export function statusFilePerSkill(ctx: InstallContext, ext: string, build: (skill: InstallContext["skills"][number]) => string): SkillStatus[] {
	return ctx.skills.map((skill) => {
		const file = path.join(ctx.dest, `${skill.name}.${ext}`);
		if (!fs.existsSync(file)) return { skill: skill.name, state: "missing" };
		if (!fileIsManaged(file)) return { skill: skill.name, state: "conflict" };
		return { skill: skill.name, state: fs.readFileSync(file, "utf8") === build(skill) ? "generated" : "drifted" };
	});
}

/**
 * Uninstall generated per-skill files. Removes files that carry our marker; an
 * unmanaged file of the same name is left alone unless `--force`, which backs it
 * up (moves it aside) rather than deleting it.
 *
 * @param ctx - Install context.
 * @param ext - File extension (no dot).
 * @returns The recorded actions.
 */
export function uninstallFilePerSkill(ctx: InstallContext, ext: string): Action[] {
	return ctx.skills.flatMap((skill) => {
		const file = path.join(ctx.dest, `${skill.name}.${ext}`);
		if (!fs.existsSync(file)) return [];
		if (fileIsManaged(file)) {
			if (!ctx.dryRun) fs.rmSync(file, { force: true });
			return [{ verb: "remove", path: file }];
		}
		if (ctx.force) return [backup(file, Date.now(), ctx.dryRun)];
		return [{ verb: "skip", path: file, note: "not managed by agent-skills — use --force to remove" }];
	});
}
