import fs from "node:fs";
import type { Action } from "../core/install-fs.js";

/** Marker placed in generated per-skill files so uninstall only removes our own files. */
export const MANAGED_LINE = "<!-- generated by agent-skills — edit the source skill, not this file -->";

/**
 * Render a flat frontmatter block from string/boolean values. Deterministic and
 * dependency-free (values are single-line only, which suits skill metadata).
 *
 * @param fields - Ordered key/value pairs (undefined values are skipped).
 * @returns A `---`-delimited YAML frontmatter block, no trailing newline.
 */
export function frontmatter(fields: Record<string, string | boolean | undefined>): string {
	const lines = ["---"];
	for (const [key, value] of Object.entries(fields)) {
		if (value === undefined) continue;
		lines.push(typeof value === "boolean" ? `${key}: ${value}` : `${key}: ${escapeYaml(value)}`);
	}
	lines.push("---");
	return lines.join("\n");
}

function escapeYaml(value: string): string {
	// Quote if the value contains YAML-significant characters.
	if (/^[\w .,/()'#&+-]+$/.test(value) && !/^[>|@`]/.test(value)) return value;
	return JSON.stringify(value);
}

/**
 * Remove a generated per-skill file only if it carries our managed marker —
 * never deletes a user's hand-written file of the same name.
 *
 * @param file - Candidate file to remove.
 * @param dryRun - When true, only record the action.
 * @returns The recorded action, or null if the file isn't ours / doesn't exist.
 */
export function removeIfManaged(file: string, dryRun: boolean): Action | null {
	if (!fs.existsSync(file)) return null;
	if (!fs.readFileSync(file, "utf8").includes(MANAGED_LINE)) return { verb: "skip", path: file, note: "not managed by agent-skills" };
	if (!dryRun) fs.rmSync(file, { force: true });
	return { verb: "remove", path: file };
}
