import fs from "node:fs";
import path from "node:path";
import type { Action } from "../core/install-fs.js";
import { writeFile } from "../core/install-fs.js";
import type { InstallContext } from "./types.js";

/** Marker placed in generated per-skill files so uninstall only removes our own files. */
export const MANAGED_LINE = "<!-- generated by agent-skills — edit the source skill, not this file -->";

/**
 * Render a flat frontmatter block from string/boolean values. Deterministic and
 * dependency-free (values are single-line only, which suits skill metadata).
 *
 * @param fields - Ordered key/value pairs (undefined values are skipped).
 * @returns A `---`-delimited YAML frontmatter block, no trailing newline.
 */
export function frontmatter(fields: Record<string, string | boolean | undefined>): string {
	const lines = ["---"];
	for (const [key, value] of Object.entries(fields)) {
		if (value === undefined) continue;
		lines.push(typeof value === "boolean" ? `${key}: ${value}` : `${key}: ${escapeYaml(value)}`);
	}
	lines.push("---");
	return lines.join("\n");
}

/**
 * Quote a frontmatter value unless it's a plain scalar free of every
 * YAML-significant character. The unquoted set deliberately excludes `:`, `#`,
 * `&`, and other indicators, so a description like "Out of scope: …" or one with
 * a "#tag" is JSON-quoted rather than emitted as invalid/misparsed YAML.
 *
 * @param value - The raw value.
 * @returns The value, quoted only if it needs to be.
 */
function escapeYaml(value: string): string {
	return /^[\w .,/()'+-]+$/.test(value) ? value : JSON.stringify(value);
}

/**
 * Install one generated file per skill under `ctx.dest`, e.g. `<name>.mdc`.
 * Shared by the file-per-skill adapters (cursor, windsurf).
 *
 * @param ctx - Install context.
 * @param ext - File extension (no dot).
 * @param build - Renders a skill's file contents.
 * @returns The recorded actions.
 */
export function installFilePerSkill(ctx: InstallContext, ext: string, build: (skill: InstallContext["skills"][number]) => string): Action[] {
	return ctx.skills.map((skill) => writeFile(path.join(ctx.dest, `${skill.name}.${ext}`), build(skill), ctx.dryRun));
}

/**
 * Uninstall generated per-skill files, removing only files that carry our marker.
 *
 * @param ctx - Install context.
 * @param ext - File extension (no dot).
 * @returns The recorded actions.
 */
export function uninstallFilePerSkill(ctx: InstallContext, ext: string): Action[] {
	return ctx.skills.map((skill) => removeIfManaged(path.join(ctx.dest, `${skill.name}.${ext}`), ctx.dryRun)).filter((a): a is Action => a !== null);
}

/**
 * Remove a generated per-skill file only if it carries our managed marker —
 * never deletes a user's hand-written file of the same name.
 *
 * @param file - Candidate file to remove.
 * @param dryRun - When true, only record the action.
 * @returns The recorded action, or null if the file doesn't exist.
 */
export function removeIfManaged(file: string, dryRun: boolean): Action | null {
	if (!fs.existsSync(file)) return null;
	if (!fs.readFileSync(file, "utf8").includes(MANAGED_LINE)) return { verb: "skip", path: file, note: "not managed by agent-skills" };
	if (!dryRun) fs.rmSync(file, { force: true });
	return { verb: "remove", path: file };
}
