import fs from "node:fs";
import path from "node:path";
import { findRepoRoot, loadConfig } from "../src/core/config.js";
import { discoverSkills } from "../src/core/registry.js";

/**
 * Regenerate the skill docs from the corpus so they never drift from the source
 * SKILL.md. Emits the catalog `docs/SKILLS.md` plus one browsable page per skill
 * under `docs/skills/<name>.md`. Run with `pnpm docs:gen`; CI checks it's fresh.
 */
const root = findRepoRoot();
const skills = discoverSkills(path.join(root, loadConfig(root).skillsDir));

const version = (s: (typeof skills)[number]): string | undefined => (typeof s.frontmatter.version === "string" ? s.frontmatter.version : undefined);

// --- Catalog: docs/SKILLS.md ---------------------------------------------------
const catalog = [
	"# Skills catalog",
	"",
	"> Generated by `pnpm docs:gen` from `skills/*/SKILL.md` — do not edit by hand.",
	"",
	`The ${skills.length} skills in this repo, alphabetically. Each description doubles as the`,
	'skill\'s "when to use" trigger. For the workflow and how the skills connect, see',
	"[OVERVIEW.md](OVERVIEW.md). Each heading links to the full generated page.",
	"",
];

for (const skill of skills) {
	const ver = version(skill) ? ` \`v${version(skill)}\`` : "";
	catalog.push(`## [${skill.name}](skills/${skill.name}.md)${ver}`, "", skill.frontmatter.description, "");
}

const catalogOut = path.join(root, "docs", "SKILLS.md");
fs.writeFileSync(catalogOut, catalog.join("\n").trimEnd() + "\n", "utf8");

// --- Per-skill pages: docs/skills/<name>.md ------------------------------------
const skillsDocDir = path.join(root, "docs", "skills");
// Rebuild the dir from scratch so a removed skill's page doesn't linger.
fs.rmSync(skillsDocDir, { recursive: true, force: true });
fs.mkdirSync(skillsDocDir, { recursive: true });

for (const skill of skills) {
	const page = [
		`# ${skill.name}`,
		"",
		`> Generated by \`pnpm docs:gen\` from \`skills/${skill.name}/SKILL.md\` — do not edit by hand.`,
		"",
		...(version(skill) ? [`**Version:** ${version(skill)}`, ""] : []),
		`_${skill.frontmatter.description}_`,
		"",
		"---",
		"",
		skill.body,
	];
	fs.writeFileSync(path.join(skillsDocDir, `${skill.name}.md`), page.join("\n").trimEnd() + "\n", "utf8");
}

console.log(`Wrote ${path.relative(root, catalogOut)} + ${skills.length} pages in ${path.relative(root, skillsDocDir)}/`);
