import fs from "node:fs";
import path from "node:path";
import { findRepoRoot, loadConfig } from "../src/core/config.js";
import { discoverSkills } from "../src/core/registry.js";

/**
 * Regenerate docs/SKILLS.md from the skill corpus so the catalog never drifts
 * from the source SKILL.md frontmatter. Run with `pnpm docs:gen`; CI checks it's fresh.
 */
const root = findRepoRoot();
const skills = discoverSkills(path.join(root, loadConfig(root).skillsDir));

const lines = [
	"# Skills catalog",
	"",
	"> Generated by `pnpm docs:gen` from `skills/*/SKILL.md` — do not edit by hand.",
	"",
	`The ${skills.length} skills in this repo, alphabetically. Each description doubles as the`,
	'skill\'s "when to use" trigger. For the workflow and how the skills connect, see',
	"[OVERVIEW.md](OVERVIEW.md).",
	"",
];

for (const skill of skills) {
	lines.push(`## ${skill.name}`, "", skill.frontmatter.description, "");
}

const out = path.join(root, "docs", "SKILLS.md");
fs.writeFileSync(out, lines.join("\n").trimEnd() + "\n", "utf8");
console.log(`Wrote ${path.relative(root, out)} (${skills.length} skills)`);
