import fs from "node:fs";
import path from "node:path";
import { findRepoRoot, loadConfig } from "../src/core/config.js";
import { discoverSkills } from "../src/core/registry.js";
import { extractSkillRefs } from "../src/core/skill.js";

/**
 * Regenerate the skill docs from the corpus so they never drift from the source
 * SKILL.md. Emits the catalog `docs/SKILLS.md` plus one browsable page per skill
 * under `docs/skills/<name>.md`. Run with `pnpm docs:gen`; CI checks it's fresh.
 */
const root = findRepoRoot();
const skills = discoverSkills(path.join(root, loadConfig(root).skillsDir));
const names = new Set(skills.map((s) => s.name));

const version = (s: (typeof skills)[number]): string | undefined => (typeof s.frontmatter.version === "string" ? s.frontmatter.version : undefined);

// Verbs that introduce a handoff clause. Word-boundaried so "feeds" doesn't match
// inside "feedback"; "hands back to" is a handoff too (e.g. ed-pr-fix → ed-ship).
const HANDOFF_VERB = /\b(hands? (?:off|back) to|routes? to|feeds?)\b/i;

/**
 * The skills a given skill hands off to, read from the handoff clause of its
 * description (the text from the first `hands off/back to` / `routes to` / `feeds`
 * onward) — so we get successors, not the predecessors it also names.
 *
 * @param skill - The skill whose handoffs to extract.
 * @returns The target skill ids, deduped, excluding self and unknown names.
 */
function handoffTargets(skill: (typeof skills)[number]): string[] {
	const desc = skill.frontmatter.description;
	const verb = HANDOFF_VERB.exec(desc);

	if (!verb) return [];

	const targets = new Set<string>();

	for (const ref of extractSkillRefs(desc.slice(verb.index))) {
		if (ref !== skill.name && names.has(ref)) targets.add(ref);
	}

	return [...targets];
}

// --- Catalog: docs/SKILLS.md ---------------------------------------------------
const catalog = [
	"# Skills catalog",
	"",
	"> Generated by `pnpm docs:gen` from `skills/*/SKILL.md` — do not edit by hand.",
	"",
	`The ${skills.length} skills in this repo, alphabetically. Each description doubles as the`,
	'skill\'s "when to use" trigger. For the workflow and how the skills connect, see',
	"[OVERVIEW.md](OVERVIEW.md). Each heading links to the full generated page.",
	"",
];

for (const skill of skills) {
	const ver = version(skill) ? ` \`v${version(skill)}\`` : "";

	catalog.push(`## [${skill.name}](skills/${skill.name}.md)${ver}`, "", skill.frontmatter.description, "");
}

const catalogOut = path.join(root, "docs", "SKILLS.md");

fs.writeFileSync(catalogOut, catalog.join("\n").trimEnd() + "\n", "utf8");

// --- Per-skill pages: docs/skills/<name>.md ------------------------------------
const skillsDocDir = path.join(root, "docs", "skills");

// Rebuild the dir from scratch so a removed skill's page doesn't linger.
fs.rmSync(skillsDocDir, { recursive: true, force: true });
fs.mkdirSync(skillsDocDir, { recursive: true });

for (const skill of skills) {
	const page = [
		`# ${skill.name}`,
		"",
		`> Generated by \`pnpm docs:gen\` from \`skills/${skill.name}/SKILL.md\` — do not edit by hand.`,
		"",
		...(version(skill) ? [`**Version:** ${version(skill)}`, ""] : []),
		`_${skill.frontmatter.description}_`,
		"",
		"---",
		"",
		skill.body,
	];

	fs.writeFileSync(path.join(skillsDocDir, `${skill.name}.md`), page.join("\n").trimEnd() + "\n", "utf8");
}

// --- Handoff map: docs/SKILL-MAP.md --------------------------------------------
const nodeId = (name: string): string => name.replace(/-/g, "_");
const edges = skills.flatMap((skill) => handoffTargets(skill).map((target) => ({ from: skill.name, to: target })));

const mermaid = [
	"```mermaid",
	"flowchart LR",
	...skills.map((skill) => `  ${nodeId(skill.name)}["${skill.name}"]`),
	...edges.map((edge) => `  ${nodeId(edge.from)} --> ${nodeId(edge.to)}`),
	"```",
];

const handoffList = skills.map((skill) => {
	const targets = handoffTargets(skill);

	return `- **${skill.name}** → ${targets.length ? targets.map((t) => `\`${t}\``).join(", ") : "_(terminal)_"}`;
});

const map = [
	"# Skill map",
	"",
	"> Generated by `pnpm docs:gen` from `skills/*/SKILL.md` — do not edit by hand.",
	"",
	"How the skills hand off to one another. Edges come from each skill's handoff clause",
	"(`hands off to`, `hands back to`, `routes to`, or `feeds`); a few skills are terminal",
	"(they close a loop rather than start the next one). For the phase tour, see [OVERVIEW.md](OVERVIEW.md).",
	"",
	...mermaid,
	"",
	"## Handoffs",
	"",
	...handoffList,
];

const mapOut = path.join(root, "docs", "SKILL-MAP.md");

fs.writeFileSync(mapOut, map.join("\n").trimEnd() + "\n", "utf8");

console.log(
	`Wrote ${path.relative(root, catalogOut)}, ${path.relative(root, mapOut)} + ${skills.length} pages in ${path.relative(root, skillsDocDir)}/`,
);
